Fix time report and skipping of tests for Allegro Common Lisp
joaotavora/fiasco pull request #31
Opened 2020-05-13 17:51 UTC by hineios

The execution registers the internal run time, but I believe it should register the real time.

Additionally, the skip functionality is broken in ACL.
Probably due to differences in behaviour for the continue restart that warnings automatically provide.
By providing and using an explicit restart, we can avoid the problem.

2020-05-13 23:24 UTC, joaotavora commented
Hullo hullo, long time no see/read!!! 

Well, the two things are quite unrelated:

1. I think the "test execution times" commit is fine.  Please make that a separate PR.

2. Regarding the second one, I'll have to take a much closer look, but it doesn't look bad.  I still access to an ACL, so maybe you can put together a small recipe to demonstrate the problem.

2020-05-13 23:40 UTC, joaotavora commented
> Regarding the second one, I'll have to take a much closer look, but it doesn't look bad. I still access to an ACL, so maybe you can put together a small recipe to demonstrate the problem.

I think I've reproduced the problem. It seems there something in ACL which doesn't establish the  `continue` restart.  Am I dreaming or did @luismbo tell me about this earlier?

2020-05-13 23:57 UTC, hineios commented
>Hullo hullo, long time no see/read!!!
Yeah, its been a while! 😄 

> Please make that a separate PR.
Yes, I should have made this two separate pull requests, sorry.
First thing tomorrow!

As for the restart problems, it seems that ACL isn't properly setting the `continue` restart for warnings.
Either way, I don't understand why you would use a warning in this situation. Well, to take advantage of the default restarts, but other than that, we can do fine with a "regular" condition, or am I missing something?
The same could be said about `test-assertion`s, but I diverge.

> Am I dreaming or did @luismbo tell me about this earlier?
Probably, we were just talking about this earlier today 🤓

2020-05-14 00:12 UTC, joaotavora commented
> As for the restart problems, it seems that ACL isn't properly setting the continue restart for warnings.

The thing is, SBCL doesn't have a continue restart for warnings either, all that implementations are required to do is establish `muffle-warning` restarts for warnings.  So I think this bit of fiasco was designed to invoke the `continue` restart established by `run-test-body-in-handlers`.

But for some reason it isn't happening in ACL.  Maybe the restart isn't active, or something else is happening.

2020-05-14 00:42 UTC, joaotavora commented
> But for some reason it isn't happening in ACL. Maybe the restart isn't active, or something else is happening.

Mystery solved.  `warn` on ACL, not only establishes the `muffle-warning` restart, but it also establishes a (pretty useless?) `continue` restart.  Our `(continue)` call invokes _that_ one, not the one we want.

2020-05-14 10:53 UTC, joaotavora requested changes
See my comments. And if you prefer a one-word change to solve this:
```
diff --git a/src/asserts.lisp b/src/asserts.lisp
index 0220cd6..30fc937 100644
--- a/src/asserts.lisp
+++ b/src/asserts.lisp
@@ -218,7 +218,7 @@ there a superfulous quote at ~S?)" condition-type))
                            :format-arguments ,whole))))))
 
 (defun skip ()
-  (warn 'test-skipped))
+  (signal 'test-skipped))
 
 (defmacro skip-unless (condition)
   `(unless ,condition (skip)))
```

2020-05-14 15:07 UTC, hineios commented on src/test.lisp
> +			  (with-simple-restart (continue-skipped-test "Skip current test")
I did the refactor. I think I did want you meant.

2020-05-14 15:11 UTC, joaotavora approved these changes
OK, great. Thanks!  Final question: does this work, did you test the other restarts?

2020-05-14 15:11 UTC, joaotavora commented on src/test.lisp
> -              (let* ((*package* (package-of test))
You also fixed indentation here.   That's OK because it totally sucked. :rofl:

2020-05-14 15:30 UTC, joaotavora commented
OOps, it seems like you broke something.  Fiasco's self-test suite is failing in a spot.  Can you check what's going on?  This is the link to the log: https://travis-ci.org/github/joaotavora/fiasco/builds/687060765

2020-05-14 15:39 UTC, hineios commented
These were my tests both in ACL and SBCL:

```(fiasco:define-test-package my-test-suite (:use :cl :fiasco))

(in-package :my-test-suite)

(define-condition my-condition () ())

(deftest normal-test ()
  (is (= 42 (* 6 7)))
  (is (not (= 42 43))))

(deftest skipping-test ()
		 (skip)
  (is (= 42 (* 6 7))))

(deftest test-with-error ()
  (is (= 0 (asdlfjh))))

(deftest error-testing ()
  (not-signals error
    (error "random error")))

(deftest signals-testing ()
  (signals my-condition
    (signal 'my-condition)))

MY-TEST-SUITE> (fiasco:all-tests)
NIL
(#<test-run of ALL-TESTS: 7 tests, 5 assertions, 2 failures in 0.0 sec (1 failed assertion, 1 error, none expected)>)
ALL-TESTS (Suite)
  MY-TEST-SUITE (Suite)
    TEST-WITH-ERROR.......................................................[FAIL]
    NORMAL-TEST...........................................................[ OK ]
    SKIPPING-TEST.........................................................[SKIP]
    SIGNALS-TESTING.......................................................[ OK ]
    ERROR-TESTING.........................................................[FAIL]


Test run had 2 failures:

  Failure 1: UNWANTED-CONDITION when running ERROR-TESTING
    ((ERROR "random error")) signaled an unwanted condition #<SIMPLE-ERROR
                                                              @
                                                              #x2036a8752>

  Failure 2: UNEXPECTED-ERROR when running TEST-WITH-ERROR
    attempt to call `ASDLFJH' which is an undefined function.
```

All seems ok.

I'll look into the Travis build.

2020-05-14 16:00 UTC, hineios commented
Test nesting seems to have something to do with the error.
The nested test in `FIASCO-BASIC-SELF-TESTS::ASSERTIONS` seems to be escaping to the new `SKIP-TEST` restart.

Maybe some more _ugliness_ is necessary to allow for this kind of shenanigans?

2020-05-14 16:09 UTC, joaotavora commented
> Maybe some more ugliness is necessary to allow for this kind of shenanigans?

Better not.  Lemme see what can be done.

2020-05-14 16:14 UTC, closed without merging

2020-05-14 16:15 UTC, joaotavora commented
Let's see if I fixed it.

2020-05-14 16:18 UTC, joaotavora commented
Seems to pass the test suite, and apparently passes your test suite on ACL, too.

2020-05-14 16:20 UTC, joaotavora commented
The real way to fix this is to rewrite fiasco from scratch, keeping the interface, but ditching the inherited cruft from stefil. A kind of "micro-fiasco".  It's something that I may or may not have done in the recent past...